version: '3'
services:
  flask-api:
    build:
      context: ./api
      dockerfile: Dockerfile  
    ports :
      - "5000:5000"
    networks:
      my_network:
        ipv4_address: 172.19.0.10
    volumes:
      - ./api:/app
  flask-serveur:
    build:
      context: ./serveur
      dockerfile: Dockerfile  
    ports :
      - "8000:8000"
    networks:
      my_network:
        ipv4_address: 172.19.0.11
    volumes:
      - ./serveur:/app
networks:
  my_network:
    ipam:
      config:
        - subnet: 172.19.0.0/16
